config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  get 'reservations/:id/confirm' => 'reservations#confirm', as: :confirm
  get 'reservations/:id/cancel' => 'reservations#cancel', as: :cancel
  get 'reservationshistory' => 'reservations#history', as: :history
  get 'rooms/update' => 'rooms#update'
  get 'rooms' => 'rooms#index'
  get 'rooms/delete' => 'rooms#delete'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  enum payment_method: [:cash, :bank]
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy, :confirm, :cancel]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.where(status: 'new').order(:create_date)
  end

  # GET /reservationshistory
  def history
    @reservations = Reservation.where.not(status: 'new').order(:create_date)
    @history = true
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # GET /reservations/1/submit
  def confirm
    @reservation.status = 'confirmed'
    
    respond_to do |format|
      if @reservation.save()
        format.html { redirect_to reservations_url, notice: 'Reservation was successfully confirmed.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /reservations/1/cancel
  def cancel
    @reservation.status = 'cancelled'
    
    respond_to do |format|
      if @reservation.save()
        format.html { redirect_to reservations_url, notice: 'Reservation was successfully cancelled' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.status = 'new'
    @reservation.create_date = Time.now
    respond_to do |format|
      if @reservation.save
        @notice = I18n.t('reservation.success_text')
        format.html { render :success, notice: I18n.t('reservation.success_text') }
        format.json { render :success, status: :ok, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:checkin, :checkout, :client_names, :client_email, :client_phone, :details,
        :clients_count, :breakfast, :payment_method, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action only: [:update, :index]

  # GET /rooms/
  def index
    @rooms = Room.all
  end

  # GET /rooms/update
  def update
    @room = Room.where(external_id: room_params[:external_id]).distinct
    if @room.empty?
      @room = Room.new(room_params)
      @room.external_id = room_params[:external_id]
    else
      @room = @room[0]
    end
    @room.name_bg = room_params[:name_bg]
    @room.name_en = room_params[:name_en]
    @room.price = room_params[:price]
    
    respond_to do |format|
      if @room.save
        format.html { redirect_to "/rooms" }
        format.json { head :no_content }
      else
        format.html { redirect_to "/rooms", notice: "Not saved."}
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /rooms/delete?external_id=?
  def delete
    @room = Room.where(external_id: room_params[:external_id]).distinct
    if @room.empty?
      respond_to do |format|
        format.html { redirect_to "/rooms", notice: "Not existing room with such external_id."}
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    else
      @room = @room[0]
      @room.destroy
      respond_to do |format|
        format.html { redirect_to "/rooms" }
        format.json { head :no_content }
      end
    end
  end

  private
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.permit(:external_id, :name_bg, :name_en, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resmodule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<style type="text/css">
  form.edit_reservation {
    width: 800px;
  }
  div.field {
    width: 400px;
    height: 40px;
  }
  div.field_container {
    float: left;
    width: 400px;
  }
</style>

<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field_container left">
    <div class="field">
      <%= f.label :checkin %><br>
      <%= f.date_select :checkin %>
    </div>
    <div class="field">
      <%= f.label :checkout %><br>
      <%= f.date_select :checkout %>
    </div>
    <div class="field">
      <%= f.label :details %><br>
      <%= f.text_field :details %>
    </div>
    <div class="field">
      <%= f.label :room_type %><br>
      <%= f.select :room_id, options_for_select(Room.all.collect { |r| [r.send(:"name_#{I18n.locale}").to_s + " (#{r.price} BGN)", r.id] }, selected: @reservation.room_id) %>
    </div>
    <div class="field">
      <%= f.label :breakfast %><br>
      <%= f.check_box :breakfast %>
    </div>  
  </div>
  <div class="field_container right">
    <div class="field">
      <%= f.label :client_names %><br>
      <%= f.text_field :client_names %>
    </div>
    <div class="field">
      <%= f.label :client_email %><br>
      <%= f.text_field :client_email %>
    </div>
    <div class="field">
      <%= f.label :client_phone %><br>
      <%= f.text_field :client_phone %>
    </div>
    <div class="field">
      <%= f.label :clients_count %><br>
      <%= f.number_field :clients_count %>
    </div>
    <div class="field">
      <%= f.label :payment_method %><br>
      <%= f.select :payment_method, options_for_select(Reservation.payment_methods.collect { |s| [t("reservation.payment_method.#{s[0]}"), s[0]] }, selected: @reservation.payment_method), {} %>
    </div>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/_list.html.erb
<table>
  <thead>
    <tr>
      <th><%= t 'helpers.label.reservation.create_date' %></th>
      <th><%= t 'helpers.label.reservation.checkin' %></th>
      <th><%= t 'helpers.label.reservation.checkout' %></th>
      <th><%= t 'helpers.label.reservation.client_names' %></th>
      <th><%= t 'helpers.label.reservation.client_email' %></th>
      <th><%= t 'helpers.label.reservation.client_phone' %></th>
      <% if @history %>
        <th><%= t 'helpers.label.reservation.status' %></th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.create_date %></td>
        <td><%= reservation.checkin %></td>
        <td><%= reservation.checkout %></td>
        <td><%= reservation.client_names %></td>
        <td><%= reservation.client_email %></td>
        <td><%= reservation.client_phone %></td>
        <% if @history %>
          <td><%= t :"reservation.status.#{reservation.status}" %></td>
        <% end %>
        <td><%= link_to t('reservation.actions.show'), reservation %></td>
        <td><%= link_to t('reservation.actions.edit'), edit_reservation_path(reservation) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reservations/edit.html.erb
<h1><%= t 'reservation.actions.edit' %></h1>

<%= render 'form' %>

<strong><%= t 'reservation.actions.actions' %>:</strong>
<%= link_to t('reservation.actions.confirm'), confirm_url(@reservation) %>
<%= link_to t('reservation.actions.cancel'), cancel_url(@reservation) %>
<br />
<%= link_to t('reservation.actions.back'), reservations_path %>

app/views/reservations/history.html.erb
<h1><%= t 'reservation.actions.list_of_processed' %></h1>
<p id="notice"><%= notice %></p>

<%= render 'list' %>

<%= link_to t('reservation.actions.list'), reservations_path %>

app/views/reservations/index.html.erb
<h1><%= t 'reservation.actions.list' %></h1>
<p id="notice"><%= notice %></p>
<%= render 'list' %>
<%= link_to t('reservation.actions.list_of_processed'), history_url %>

app/views/reservations/new.html.erb
<h1><%= t 'reservation.actions.new' %></h1>

<%= render 'form' %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t 'helpers.label.reservation.create_date' %>:</strong>
  <%= @reservation.create_date %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.checkin' %>:</strong>
  <%= @reservation.checkin %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.checkout' %>:</strong>
  <%= @reservation.checkout %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.client_names' %>:</strong>
  <%= @reservation.client_names %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.client_email' %>:</strong>
  <%= @reservation.client_email %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.client_phone' %>:</strong>
  <%= @reservation.client_phone %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.details' %>:</strong>
  <%= @reservation.details %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.clients_count' %>:</strong>
  <%= @reservation.clients_count %>
</p>


<p>
  <strong><%= t 'helpers.label.reservation.room_type' %>:</strong>
  <%= @reservation.room ? @reservation.room.send(:"name_#{I18n.locale}").to_s + " (#{@reservation.room.price} BGN)" : "" %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.breakfast' %>:</strong>
  <%= @reservation.breakfast %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.payment_method' %>:</strong>
  <%= t("reservation.payment_method.#{@reservation.payment_method}") %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.status' %>:</strong>
  <%= t("reservation.status.#{@reservation.status}") %>
</p>

<strong><%= t 'reservation.actions.actions' %>:</strong>
<%= link_to t('reservation.actions.confirm'), confirm_url(@reservation) %>
<%= link_to t('reservation.actions.cancel'), cancel_url(@reservation) %>
<br />
<%= if @reservation.status == 'new' then link_to t('reservation.actions.edit'), edit_reservation_path(@reservation) end %>
<%= @reservation.status == 'new' ? link_to(t('reservation.actions.back'), reservations_path) : link_to(t('reservation.actions.back'), history_url) %>

app/views/reservations/success.html.erb
<p id="notice"><%= @notice %></p>

<p>
  <strong><%= t 'helpers.label.reservation.create_date' %>:</strong>
  <%= @reservation.create_date %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.checkin' %>:</strong>
  <%= @reservation.checkin %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.checkout' %>:</strong>
  <%= @reservation.checkout %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.client_names' %>:</strong>
  <%= @reservation.client_names %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.client_email' %>:</strong>
  <%= @reservation.client_email %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.client_phone' %>:</strong>
  <%= @reservation.client_phone %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.details' %>:</strong>
  <%= @reservation.details %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.clients_count' %>:</strong>
  <%= @reservation.clients_count %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.breakfast' %>:</strong>
  <%= @reservation.breakfast %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.payment_method' %>:</strong>
  <%= t("reservation.payment_method.#{@reservation.payment_method}") %>
</p>

<p>
  <strong><%= t 'helpers.label.reservation.status' %>:</strong>
  <%= t("reservation.status.#{@reservation.status}") %>
</p>

app/views/rooms/index.html.erb
<table>

  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.external_id %></td>
      <td><%= room.name_bg %></td>
      <td><%= room.name_en %></td>
      <td><%= room.price %></td>
    </tr>
  <% end %>
</table>

<br>